---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: customerpwa-frontend-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mern-stack-client
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 54301
      protocol: TCP
      name: https
  selector:
    app: mern-stack
